// Code generated by protoc-gen-go.
// source: madridmas.proto
// DO NOT EDIT!

package madridmas_proto

import "github.com/golang/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SendIncidentRequest struct {
	// latitude is part of the incident location.
	Latitude *float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	// longitude is part of the incident location.
	Longitude *float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	// description is the user description in text for
	// the incident reported.
	Description      *string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SendIncidentRequest) Reset()         { *m = SendIncidentRequest{} }
func (m *SendIncidentRequest) String() string { return proto.CompactTextString(m) }
func (*SendIncidentRequest) ProtoMessage()    {}

func (m *SendIncidentRequest) GetLatitude() float64 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *SendIncidentRequest) GetLongitude() float64 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *SendIncidentRequest) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type SendIncidentResponse struct {
	// error is empty in case the request was succesful.
	Error            *string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SendIncidentResponse) Reset()         { *m = SendIncidentResponse{} }
func (m *SendIncidentResponse) String() string { return proto.CompactTextString(m) }
func (*SendIncidentResponse) ProtoMessage()    {}

func (m *SendIncidentResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func init() {
}
